---
- hosts: all
  become: yes
  tasks:
  - name: Add Proxmox repository into sources list
    ansible.builtin.apt_repository:
      repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
      state: present
  
  - name: Add Ceph repository into sources list
    ansible.builtin.apt_repository:
      repo: deb http://download.proxmox.com/debian/ceph-quincy bullseye main
      state: present
  
  - name: Update System 
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 0
      name: "*"
      state: latest

  - name: Install Proxmox-VE
    ansible.builtin.apt:
      state: present
      pkg:
      - proxmox-ve
    

  - name: Remove OS-prober
    ansible.builtin.apt:
      state: absent
      name: os-prober
      
  - name: Reboot host into proxmox
    ansible.builtin.reboot:
      